server:
  port: 8080

#  tomcat:
#    max-connections: 50000
#    accept-count: 2000
#    threads:
#      max: 30

spring:

  application:
    name: pathfinder

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"

#    vm Option to set user and pass and not expose it
    username: ${db_username}
    password: ${db_password}

  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true



## IF Data.sql is present will initialize the data file
#  mode should be set to always, if want to read data.sql from resources
  sql:
    init:
      mode: never

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

 #Enables Virtual Threads!
 #  threads:
 #    virtual:
 #      enabled: true

#Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name: 
